//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StructuredCablingStudioCore.Parameters.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StructuredCablingStudioCore.Parameters.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string AnArbitraryNumberOfPorts_NumberOfPortsDiapason_Max {
            get {
                return ResourceManager.GetString("AnArbitraryNumberOfPorts.NumberOfPortsDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string AnArbitraryNumberOfPorts_NumberOfPortsDiapason_Min {
            get {
                return ResourceManager.GetString("AnArbitraryNumberOfPorts.NumberOfPortsDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NonRecommendations_RecommendationCableStandart {
            get {
                return ResourceManager.GetString("NonRecommendations.RecommendationCableStandart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NonRecommendations_RecommendationIsolationMaterial {
            get {
                return ResourceManager.GetString("NonRecommendations.RecommendationIsolationMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NonRecommendations_RecommendationIsolationType {
            get {
                return ResourceManager.GetString("NonRecommendations.RecommendationIsolationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NonRecommendations_RecommendationShieldedType {
            get {
                return ResourceManager.GetString("NonRecommendations.RecommendationShieldedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string NonStrictComplianceWithTheStandart_MaxPermanentLinkDiapason_Max {
            get {
                return ResourceManager.GetString("NonStrictComplianceWithTheStandart.MaxPermanentLinkDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,01.
        /// </summary>
        internal static string NonStrictComplianceWithTheStandart_MaxPermanentLinkDiapason_Min {
            get {
                return ResourceManager.GetString("NonStrictComplianceWithTheStandart.MaxPermanentLinkDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string NonStrictComplianceWithTheStandart_MinPermanentLinkDiapason_Max {
            get {
                return ResourceManager.GetString("NonStrictComplianceWithTheStandart.MinPermanentLinkDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,01.
        /// </summary>
        internal static string NonStrictComplianceWithTheStandart_MinPermanentLinkDiapason_Min {
            get {
                return ResourceManager.GetString("NonStrictComplianceWithTheStandart.MinPermanentLinkDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NonTechnologicalReserve_TechnologicalReserve {
            get {
                return ResourceManager.GetString("NonTechnologicalReserve.TechnologicalReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string NotAnArbitraryNumberOfPorts_NumberOfPortsDiapason_Max {
            get {
                return ResourceManager.GetString("NotAnArbitraryNumberOfPorts.NumberOfPortsDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string NotAnArbitraryNumberOfPorts_NumberOfPortsDiapason_Min {
            get {
                return ResourceManager.GetString("NotAnArbitraryNumberOfPorts.NumberOfPortsDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 (Cat 5), 5e (Cat 5e).
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationCableStandart_FastEthernet {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationCableStandart.FastEthernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 (Cat 6).
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationCableStandart_FiveGBASE_T {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationCableStandart.FiveGBASE_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5e (Cat 5e).
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationCableStandart_GigabitBASE_T {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationCableStandart.GigabitBASE_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 (Cat 6).
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationCableStandart_GigabitBASE_TX {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationCableStandart.GigabitBASE_TX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationCableStandart_None {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationCableStandart.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 (Cat 3), 5 (Cat 5), 5e (Cat 5e).
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationCableStandart_TenBASE_T {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationCableStandart.TenBASE_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 (Cat 6), 7 (Cat 7), 7a (Cat 7a).
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationCableStandart_TenGE {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationCableStandart.TenGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5e (Cat 5e).
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationCableStandart_TwoPointFiveGBASE_T {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationCableStandart.TwoPointFiveGBASE_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSZH, LSOH, LSHF, LSNH, NHFR, HFFR, FRZH, LSFRZH.
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationIsolationMaterial_LSZH {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationIsolationMaterial.LSZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationIsolationMaterial_None {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationIsolationMaterial.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVC, PP, PE.
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationIsolationMaterial_PVC {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationIsolationMaterial.PVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor.
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationIsolationType_Indoor {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationIsolationType.Indoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationIsolationType_None {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationIsolationType.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor.
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationIsolationType_Outdoor {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationIsolationType.Outdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP, STP, F/UTP, S/UTP, U/FTP, SF/UTP, F/FTP, S/FTP, SF/FTP.
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationShieldedType_FTP {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationShieldedType.FTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationShieldedType_None {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationShieldedType.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTP (U/UTP).
        /// </summary>
        internal static string RecommendationsAvailability_RecommendationShieldedType_UTP {
            get {
                return ResourceManager.GetString("RecommendationsAvailability.RecommendationShieldedType.UTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        internal static string StandartValues_CableHankMeterageDiapason_Max {
            get {
                return ResourceManager.GetString("StandartValues.CableHankMeterageDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,01.
        /// </summary>
        internal static string StandartValues_CableHankMeterageDiapason_Min {
            get {
                return ResourceManager.GetString("StandartValues.CableHankMeterageDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        internal static string StandartValues_NumberOfWorkplacesDiapason_Max {
            get {
                return ResourceManager.GetString("StandartValues.NumberOfWorkplacesDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string StandartValues_NumberOfWorkplacesDiapason_Min {
            get {
                return ResourceManager.GetString("StandartValues.NumberOfWorkplacesDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string StandartValues_TechnologicalReserveDiapason_Max {
            get {
                return ResourceManager.GetString("StandartValues.TechnologicalReserveDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string StandartValues_TechnologicalReserveDiapason_Min {
            get {
                return ResourceManager.GetString("StandartValues.TechnologicalReserveDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        internal static string StrictComplianceWithTheStandart_MaxPermanentLinkDiapason_Max {
            get {
                return ResourceManager.GetString("StrictComplianceWithTheStandart.MaxPermanentLinkDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string StrictComplianceWithTheStandart_MaxPermanentLinkDiapason_Min {
            get {
                return ResourceManager.GetString("StrictComplianceWithTheStandart.MaxPermanentLinkDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        internal static string StrictComplianceWithTheStandart_MinPermanentLinkDiapason_Max {
            get {
                return ResourceManager.GetString("StrictComplianceWithTheStandart.MinPermanentLinkDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string StrictComplianceWithTheStandart_MinPermanentLinkDiapason_Min {
            get {
                return ResourceManager.GetString("StrictComplianceWithTheStandart.MinPermanentLinkDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,10.
        /// </summary>
        internal static string TechnologicalReserveAvailability_TechnologicalReserve_Default {
            get {
                return ResourceManager.GetString("TechnologicalReserveAvailability.TechnologicalReserve.Default", resourceCulture);
            }
        }
    }
}
